name: Process Day One Entries

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  process-entries:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install
    
    - name: Process Day One entries
      env:
        DAYONE_EMAIL: ${{ secrets.DAYONE_EMAIL }}
        DAYONE_PASSWORD: ${{ secrets.DAYONE_PASSWORD }}
        DAYONE_JOURNAL_ID: ${{ secrets.DAYONE_JOURNAL_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run process-dayone
    
    - name: Check for changes
      id: changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.changes.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Auto-update blog from Day One entries

        $(git diff --cached --stat)
        
        🤖 Automated via GitHub Actions"
        git push
    
    - name: Trigger GitHub Pages deployment
      if: steps.changes.outputs.changes == 'true'
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type":"deploy-pages"}'
    
    - name: Create issue on error
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Day One Processing Failed',
            body: `The Day One processing workflow failed at ${new Date().toISOString()}.
            
            **Workflow Run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            Please check the logs for details.`,
            labels: ['bug', 'automation']
          })